ops:
  get_pois:
    config:
      path: pois.csv
resources:
  mapquest:
    config:
      api_key:
        env: MAPQUEST_API_KEY
  home_cache:
    config:
      path: home_cache.db
  sheet:
    config:
      spreadsheet_id: "1ipv9kPi986nDvAtw3E9twFU2z9MplMR8pELT9_Nh1KM"
      spreadsheet_gid: "1068760068"
